AY2021S1-CS2113-T13-1/tp

docs/AboutUs.md, src/main/java/seedu/duke/command/AddCommand.java, src/main/java/seedu/duke/command/Command.java, src/main/java/seedu/duke/command/DeleteCommand.java, src/main/java/seedu/duke/command/EditCommand.java, src/main/java/seedu/duke/command/ExitCommand.java, src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/HelpCommand.java, src/main/java/seedu/duke/command/ListEventCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/command/PinCommand.java, src/main/java/seedu/duke/command/RemindCommand.java, src/main/java/seedu/duke/command/TagsCommand.java, src/main/java/seedu/duke/command/ViewNoteCommand.java, src/main/java/seedu/duke/data/exception/SystemException.java, src/main/java/seedu/duke/data/notebook/Note.java, src/main/java/seedu/duke/data/notebook/Notebook.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/data/timetable/Event.java, src/main/java/seedu/duke/data/timetable/Timetable.java, src/main/java/seedu/duke/storage/IOManager.java, src/main/java/seedu/duke/ui/UIManager.java, src/main/java/seedu/duke/util/DateTime.java, src/main/java/seedu/duke/util/Parser.java
Update
*Removed John Doe from AboutUs.md
=> Add classes needed for Notus

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/AddCommand.java, src/main/java/seedu/duke/command/Command.java, src/main/java/seedu/duke/command/DeleteCommand.java, src/main/java/seedu/duke/command/EditCommand.java, src/main/java/seedu/duke/command/ExitCommand.java, src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/HelpCommand.java, src/main/java/seedu/duke/command/ListCommand.java, src/main/java/seedu/duke/command/ListEventCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/command/PinCommand.java, src/main/java/seedu/duke/command/RemindCommand.java, src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/command/TagsCommand.java, src/main/java/seedu/duke/command/ViewNoteCommand.java, src/main/java/seedu/duke/data/exception/SystemException.java, src/main/java/seedu/duke/data/notebook/Note.java, src/main/java/seedu/duke/data/notebook/Notebook.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/data/timetable/Event.java, src/main/java/seedu/duke/data/timetable/Timetable.java, src/main/java/seedu/duke/storage/IOManager.java, src/main/java/seedu/duke/storage/StorageManager.java, src/main/java/seedu/duke/ui/InterfaceManager.java, src/main/java/seedu/duke/ui/UIManager.java, src/main/java/seedu/duke/util/DateTime.java, src/main/java/seedu/duke/util/DateTimeManager.java, src/main/java/seedu/duke/util/Parser.java, text-ui-test/EXPECTED.TXT
=> Set up base code for project flow

src/main/java/seedu/duke/command/AddCommand.java, src/main/java/seedu/duke/command/EditCommand.java, src/main/java/seedu/duke/command/ListEventCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/util/Parser.java
=> Update base code and added missing class ListEventCommand

src/main/java/seedu/duke/util/Parser.java, src/test/java/seedu/duke/command/AddCommandTest.java, src/test/java/seedu/duke/command/DeleteCommandTest.java, src/test/java/seedu/duke/command/EditCommandTest.java, src/test/java/seedu/duke/command/ExitCommandTest.java, src/test/java/seedu/duke/command/FindCommandTest.java, src/test/java/seedu/duke/command/HelpCommandTest.java, src/test/java/seedu/duke/command/ListEventCommandTest.java, src/test/java/seedu/duke/command/ListNoteCommandTest.java, src/test/java/seedu/duke/command/PinCommandTest.java, src/test/java/seedu/duke/command/RemindCommandTest.java, src/test/java/seedu/duke/command/TagCommandTest.java, src/test/java/seedu/duke/command/ViewNoteCommandTest.java, src/test/java/seedu/duke/data/exception/SystemExceptionTest.java, src/test/java/seedu/duke/data/notebook/NoteTest.java, src/test/java/seedu/duke/data/notebook/NotebookTest.java, src/test/java/seedu/duke/data/notebook/TagTest.java, src/test/java/seedu/duke/data/timetable/EventTest.java, src/test/java/seedu/duke/data/timetable/TimetableTest.java, src/test/java/seedu/duke/storage/StorageManagerTest.java, src/test/java/seedu/duke/ui/InterfaceManagerTest.java, src/test/java/seedu/duke/util/DateTimeManagerTest.java, src/test/java/seedu/duke/util/ParserTest.java
=> Setup test classes for JUnit tests

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/AddCommand.java, src/main/java/seedu/duke/command/CreateTagCommand.java, src/main/java/seedu/duke/command/DeleteCommand.java, src/main/java/seedu/duke/command/DeleteTagCommand.java, src/main/java/seedu/duke/command/EditCommand.java, src/main/java/seedu/duke/command/ExitCommand.java, src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/HelpCommand.java, src/main/java/seedu/duke/command/ListEventCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/command/ListTagCommand.java, src/main/java/seedu/duke/command/PinCommand.java, src/main/java/seedu/duke/command/RemindCommand.java, src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/command/ViewNoteCommand.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/ui/InterfaceManager.java, src/main/java/seedu/duke/util/Parser.java, src/main/java/seedu/duke/util/PrefixSyntax.java, text-ui-test/EXPECTED.TXT
Closes #24 
Help function completed. Prints in alternating colors (cyan and white) to the console for enhanced visibility.
Removed console color black as it is similar/same as the default.
Renamed COLOR_CLEAR_STRING to COLOR_RESET_STRING for better clarity.
=> Add help command functionality.

src/main/java/seedu/duke/data/exception/SystemException.java, src/main/java/seedu/duke/data/notebook/Notebook.java, src/main/java/seedu/duke/storage/StorageManager.java, src/test/java/seedu/duke/storage/StorageManagerTest.java
Closes #23 
Save the note as a text file as well as the details in the main notebook.txt
=> Prachi branch save note as text file

src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/data/notebook/TagManager.java, src/main/java/seedu/duke/util/Parser.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Closes #15 
ListNodeCommand functionality implemented for the following cases:
1. list-n 
2. list-n /tag TAG /tag TAG
3. list-n up
4. list-n down
5. A combination of 2 and 3/4
=> Add functionality for ListNodeCommand

src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/main/java/seedu/duke/util/Parser.java
JavaDoc and additional comments were added in the methods associated to:
- HelpCommand
- FindCommand
- ListNoteCommand
Refactored duplicate code under the ListNoteCommand.execute()
=> Add JavaDocs

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/Command.java
=> Command classes now have an storageManager object to save notes and events accordingly.

src/main/java/seedu/duke/command/AddNoteCommand.java, src/main/java/seedu/duke/command/DeleteNoteCommand.java, src/main/java/seedu/duke/data/exception/SystemException.java, src/main/java/seedu/duke/util/Parser.java, src/main/java/seedu/duke/util/PrefixSyntax.java
Closes #13  #14 
Ive merged my previous PR #50 to this pr.
=> Minor refactor and comments on add and delete notes

src/test/java/seedu/duke/command/HelpCommandTest.java
Create a test function for HelpCommandTest
=> Junit AssertEquals Test for HelpCommand

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/AddEventCommand.java, src/main/java/seedu/duke/command/DeleteEventCommand.java, src/main/java/seedu/duke/command/DeleteNoteCommand.java, src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/PinCommand.java, src/main/java/seedu/duke/command/RemindCommand.java, src/main/java/seedu/duke/data/exception/SystemException.java, src/main/java/seedu/duke/data/timetable/Event.java, src/main/java/seedu/duke/data/timetable/Reminder.java, src/main/java/seedu/duke/data/timetable/Timetable.java, src/main/java/seedu/duke/ui/InterfaceManager.java, src/main/java/seedu/duke/util/Parser.java, text-ui-test/EXPECTED.TXT
Removed unused import statement.
Updated some of the prepare functions to throw proper SystemExceptions.
Changed all equals function to equalsIgnoreCase
=> Final clean up of code for v1.0

src/main/java/seedu/duke/command/AddNoteCommand.java, src/test/java/seedu/duke/command/AddNoteCommandTest.java, src/test/java/seedu/duke/command/DeleteNoteCommandTest.java, src/test/java/seedu/duke/util/ParserTest.java
Bring forward and merged from #61. Closed #61
=> Junit Delete, Add and deleteLine with v1.0

build.gradle, src/main/java/seedu/duke/data/timetable/Event.java, src/main/java/seedu/duke/data/timetable/Reminder.java, src/main/java/seedu/duke/data/timetable/Timetable.java, src/test/java/seedu/duke/command/AddEventCommandTest.java, src/test/java/seedu/duke/command/RemindCommandTest.java, src/test/java/seedu/duke/data/timetable/DailyEventTest.java, src/test/java/seedu/duke/data/timetable/EventTest.java, src/test/java/seedu/duke/data/timetable/MonthlyEventTest.java, src/test/java/seedu/duke/data/timetable/TimetableTest.java, src/test/java/seedu/duke/data/timetable/WeeklyEventTest.java, src/test/java/seedu/duke/data/timetable/YearlyEventTest.java
Has JUnit test for all classes in Timetable and some Event related Commands
=> Added JUnit Test for Event.

FindCommand.log, HelpCommand.log, HelpCommand.log.1, src/main/java/seedu/duke/command/FindCommand.java, src/main/java/seedu/duke/command/HelpCommand.java
Addresses #48 
Logger for FindCommand and HelpCommand. I think this is how we log for testing/debugging?
Let me know if any comments otherwise we can try to implement logging for the other classes.
=> Add logger for Find and Help Command

HelpCommand.log, HelpCommand.log.1, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/HelpCommand.java, src/main/java/seedu/duke/command/ListNoteCommand.java, src/test/java/seedu/duke/command/HelpCommandTest.java, text-ui-test/EXPECTED.TXT
Made the following changes
- Logo for NotUS
- Line breaks between commands to make it easier for the user
=> Beautified Welcome Screen

FindCommand.log, HelpCommand.log, build.gradle, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/CreateTagCommand.java, src/main/java/seedu/duke/command/HelpCommand.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/data/notebook/TagManager.java, src/test/java/seedu/duke/command/CreateTagCommandTest.java, src/test/java/seedu/duke/command/HelpCommandTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
=> Suggested fix for printing color fonts in Windows terminal

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/CreateTagCommand.java, src/main/java/seedu/duke/command/DeleteTagCommand.java, src/main/java/seedu/duke/command/ListTagCommand.java, src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/data/notebook/TagManager.java, src/main/java/seedu/duke/util/Formatter.java, src/test/java/seedu/duke/command/CreateTagCommandTest.java, src/test/java/seedu/duke/command/DeleteTagCommandTest.java, src/test/java/seedu/duke/command/TagCommandTest.java, src/test/java/seedu/duke/data/notebook/TagManagerTest.java, text-ui-test/EXPECTED.TXT
=> Update Formatter class

.gitignore, build.gradle, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/command/CreateTagCommand.java, src/main/java/seedu/duke/command/DeleteTagCommand.java, src/main/java/seedu/duke/command/ListTagCommand.java, src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/ui/Formatter.java, src/test/java/seedu/duke/command/DeleteTagCommandTest.java, src/test/java/seedu/duke/command/TagCommandTest.java
=> Added jansi library to allow printing of text font in windows terminal

docs/DeveloperGuide.md, docs/README.md, docs/UserGuide.md
Addresses #42 
Updated the following in the user guide:
- Table of Contents (for quick access)
- Introduction
- Quick Start
- Features List
- FAQ
- Command Summary
Following changes in the dev guide:
- Table of Contents (standardize sizing across documents)
Changes in the docs/README:
- NotUS product intro
Requires further updates but I think it is good to go for a starter!
=> Update User Guide

src/main/java/seedu/duke/command/TagCommand.java, src/main/java/seedu/duke/data/notebook/Tag.java, src/main/java/seedu/duke/data/notebook/TagManager.java
=> Added assertion and logging for tag related functions

docs/diagrams/AddNote_Sequence.puml
=> Sequence diagram for add note

src/main/java/seedu/duke/command/PinCommand.java, src/main/java/seedu/duke/command/ViewNoteCommand.java
=> Prachi branch pin and view note logging

docs/UserGuide.md, src/main/java/seedu/notus/command/PinCommand.java, src/main/java/seedu/notus/data/notebook/Note.java
Additionally, I fixed the user guide in case the user enters both parameters.
=> Prachi branch pin unpin phrasing

docs/UserGuide.md
Closes #146, Closes #147. Removed four other instances of HH:mm:SS found as well.
=> Updated DateTime Format issues on User Guide.

src/main/java/seedu/notus/command/AddEventCommand.java, src/main/java/seedu/notus/data/timetable/Event.java
Missed edge case of same timeslot as well as issue after merging causing all events to compare to itself and flagged as duplicate.
=> Quick fix for edge case & issue from auto-merge

data/archived_notebook.txt, src/test/java/seedu/notus/command/ArchiveNoteCommandTest.java, src/test/java/seedu/notus/command/PinCommandTest.java
Fix the junit test for pin and archive note command
=> Prachi branch j unit test

docs/team/chongjx.md, docs/team/nazryl.md, docs/team/r-ramana.md
Will merge this with no review as it is only some minor adjustments visually.
=> Clean Up docs

docs/team/brandonywl.md, docs/team/chongjx.md, docs/team/nazryl.md, docs/team/prachi2023.md, docs/team/r-ramana.md
Merging since no change in content and rushing for time.
=> Update PPP for breaks

docs/UserGuide.md
=> Brandon branch update UG
